### ISSUE TITLE
Program not executing

### ISSUE THREAD

**Issue by wisconsin2992** [entynetproject/phonia#12]
I am trying to use this program and keep getting the following error when I try to run it:
Traceback (most recent call last):
  File "./phonia", line 34, in <module>
    from lib.output import *
  File "/root/phonia/lib/output.py", line 27, in <module>
    from lib.colors import *
  File "/root/phonia/lib/colors.py", line 26, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

i have tried to use the "--no-ansi" but that doesn't help either. I noticed files have been updated recently and I ran the -u to update it and the same message comes up. Let me know if there is some other modification I need to do to get this to work. Thank you.

**Comment by game-lover** [comment]
pip3 install colorama

**Comment by enty8080** [comment]
Thank you, @game-lover but it is in install.sh
