### ISSUE TITLE
Error after choosing"Would you like to use an additional format for this number"

### ISSUE THREAD

**Issue by Hyp3r1onX** [entynetproject/phonia#3]
Hi,
i'm getting this error when i have to choose "Would you like to use an additional format for this number"  yes or no. Getting same error for both options yes and for no.
![phonia](https://user-images.githubusercontent.com/49735625/64288437-67661a00-cf62-11e9-8ac4-78f308fe11f6.png)
any solution for this?
Thanks and nice tool :)

**Comment by enty8080** [comment]
Thank you, we are going to fix this bug ;)

**Comment by six2dez** [comment]
This issue is still active :(

**Comment by pispuso** [comment]
I'm still having this problem.

**Comment by mluis** [comment]
+1 just testing..
