### ISSUE TITLE
 No module named 'lib.args'

### ISSUE THREAD

**Issue by rata15** [entynetproject/phonia#4]
/phonia# phonia
Traceback (most recent call last):
  File "./phonia", line 34, in <module>
    from lib.args import args,parser
ModuleNotFoundError: No module named 'lib.args'

**Comment by enty8080** [comment]
Sorry, I forgot to add `__init__.py` to `phonia/lib` and `phonia/scanners`, recheck please.

**Comment by rata15** [comment]
# ls ./lib/
__init__.py  args.py  banner.py  colors.py  format.py  googlesearch.py  logger.py  output.py  request.py

# ls ./scanners/
__init__.py  footprints.py  localscan.py  numverify.py  ovh.py  recon.py

# phonia
Traceback (most recent call last):
  File "./phonia", line 34, in <module>
    from lib.args import args,parser
ModuleNotFoundError: No module named 'lib.args'

I have same error ..

**Comment by shivanag786** [comment]
i have same error

**Comment by enty8080** [comment]
What OS do you use?
Python version?

**Comment by enty8080** [comment]
What OS do you use?

**Comment by deeppaz** [comment]
Traceback (most recent call last):
  File "./phonia", line 10, in <module>
    from lib.args import args
ModuleNotFoundError: No module named 'lib.args'
