### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ghost6-2** [entynetproject/phonia#5]
Hi there, I'm running an issue with your project, can you please help to solve it..? Im running this in Kali Linux via VMware virtual machine instance. 

./phonia -p +38521307739
[*] Fetching information for 38521307739...
[*] Running local scan...
[+] International format: +385 21 307 739
[+] Local format: 21307739
[+] Country found: Croatia (+385)
[+] City/Area: Split-Dalmatia
[+] Carrier: 
[+] Timezone: Europe/Zagreb
[+] The number is valid and possible!
[*] Running numverify scan...
[+] Number: (+385) 021307739
[+] Country: Croatia (Republic of) (HR)
[+] Location: Split-Dalmatia County
[+] Carrier: 
[+] Line type: landline
[!] This is most likely a landline, but it can still be a fixed VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[*] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/385-21-307-739
[?] Use an additional format? (y/n): y

**Traceback (most recent call last):
  File "./phonia", line 136, in <module>
    main()
  File "./phonia", line 98, in main
    scanNumber(args.phone)
  File "./phonia", line 63, in scanNumber
    osintScan(number)
  File "/root/Desktop/phonia/scanners/footprints.py", line 172, in osintScan
    askingCustomPayload = ask(
  File "/root/Desktop/phonia/lib/output.py", line 69, in ask
    sys.stdout = Logger()
  File "/root/Desktop/phonia/lib/logger.py", line 36, in __init__
    predir = os.path.split(output)[0]
  File "/usr/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType**

**Comment by enty8080** [comment]
Hi, re-clone project please, I fixed it :)
